spring:
    application:
        name: kr-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    zipkin:
      enabled: true
    sleuth:
      sampler:
        percentage: 1
server:
    port: 8765 #启动端口
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: IN_MEMORY #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 200
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:
    auth:
      path: /auth/**
      serviceId: kr-auth
    admin:
      path: /admin/**
      serviceId: kr-admin
    scientific:
      path: /scientific/**
      serviceId: kr-scientific
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 12000000
  ConnectTimeout: 12000000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000
          strategy: SEMAPHORE


gate:
  ignore:
    startWith: /static,/auth/jwt


auth:
  serviceId: kr-auth
  user:
    token-header: Bio-D-Token


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
eureka:
  instance:
    # docker 部署开启
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://kr-center:8761/eureka